#!/bin/sh
# Modificado por: Robson Vaamonde
# Script original criado por: Batocera.org
# Site: www.procedimentosemti.com.br
# Facebook: facebook.com/ProcedimentosEmTI
# Facebook: facebook.com/BoraParaPratica
# YouTube: youtube.com/BoraParaPratica
# Data de criação: 15/09/2021
# Data de atualização: 28/09/2021
# Versão: 0.04
# Testado e homologado para a versão do Linux Mint 20.2 Uma e Batocera v31
#
# Partição 1: Tipo (type) = fat32, Nome (name) = BATOCERA
# Partição 2: Tipo (type) = ext4, Nome (name) = SHARE, deve ser criada logo após a partição BATOCERA.
# Fazer o download do arquivo: boot.tar.xz e descompactá-lo na partição BATOCERA.
# Link do download do arquivo boot.tar.xz: http://batocera.org/upgrades/x86_64/stable/last/boot.tar.xz
# Copiar esse script para o diretório: /​etc/​grub.d/​15_batocera
# Aplicar as permissões: sudo chmod a+x /​etc/​grub.d/​15_batocera
# Atualizar o Grub: sudo update-grub
#
# Criação da variável de localização da Partição do Batocera Linux
# opção do comando lsblk: --fs (Output  info  about  filesystems), --noheadings (Do not print a header line)
# --pairs (Produce  output  in  the  form of key="value" pairs.), -o (output list)
# opção do comando grep: -E (extended-regexp)
# opção do comando sed: -e (script), s+ (separate)
# opção do comando head: -1 (one line)
# opção do redirecionar | (piper): Conecta a saída padrão com a entrada padrão de outro comando
# opções de expressões regulares: ^ (Circunflexo) Casa o começo da linha, $ (Cifrão) Casa o fim da linha
# \ (Escape) Escapa um meta, tirando seu poder
BATOCERA_UUID=$(lsblk --fs --noheadings --pairs -o TYPE,LABEL,UUID |
			grep -E '^TYPE="part" LABEL="BATOCERA" UUID="[^"]*"$' |
			sed -e s+'^TYPE="part" LABEL="BATOCERA" UUID="\([^"]*\)"$'+'\1'+ | 
			head -1)
#
# Teste lógico para a criação do Menu do Grub com a opção do Boot do Batocera Linux
# opção do comando test: -n (string)
if test -n "${BATOCERA_UUID}"; then
	echo "Imagem do Batocera encontrada em ${BATOCERA_UUID}" >&2
		cat <<EOF
			menuentry "Batocera Linux Retro Games" {
			insmod fat
			search --no-floppy --fs-uuid --set=root ${BATOCERA_UUID}
			linux /boot/linux label=BATOCERA console=tty3 quiet loglevel=0 vt.global_cursor_default=0
			initrd /boot/initrd.gz
			}
EOF
fi